### PR TITLE
Add a switch to enable ipv4 or ipv6.

### PR DESCRIPTION
**Pull request by wuxueyang96**
solve issue https://github.com/ClickHouse/ClickHouse/issues/33381

### CODE REVIEW

**Comment by wuxueyang96** [comment]
@alexey-milovidov @alesapin @filimonov Could you help me review this pull request?

**Review by alexey-milovidov — APPROVED** [review]

**Comment by alexey-milovidov** [comment]
Ok, but IPv6 should be by default.

**Review by alesapin — APPROVED** [review]
But we have to change clickhouse code as well?

**Comment by wuxueyang96** [comment]
> But we have to change clickhouse sources as well?

yes, i will submit pr later. thank you.

**Pull request merged**
